[build-system]
requires = ["setuptools >= 68.0.0", "rebound >= 4.0.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "cp36*"
build = "cp38*"
manylinux-x86_64-image = "manylinux2014"

[tool.uv]
no-build-isolation = true
